language: go
os: linux
dist: trusty
services:
  - docker
go: 1.11.1
python: '3.6'
before_install:
  - sudo apt-get install python3 python3-pip
install:
  - go get github.com/karalabe/xgo
  - pip3 install --user pipenv
  - pipenv sync
script: 
  - make build
  - make test