language: go
os: linux
dist: trusty
services:
  - docker
go: 1.11.1
python: '3.6'
install:
  - go get github.com/karalabe/xgo
  - 'pip3 install pipenv'
  - 'pipenv sync'
script: 
  - make build
  - make test